=== 2403717610421042-eng/webtechlab/src/main/webapp/xml/events.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="events">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="date" type="xs:string"/>
                            <xs:element name="venue" type="xs:string"/>
                            <xs:element name="maxMembers" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 2403717610421042-eng/webtechlab/src/main/webapp/xml/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="events.xsd">
    <event>
        <name>CodeFest 2026</name>
        <date>2026-11-20</date>
        <venue>CS Lab 1</venue>
        <maxMembers>100</maxMembers>
    </event>
    <event>
        <name>TechTalk 2026</name>
        <date>2026-11-22</date>
        <venue>Auditorium</venue>
        <maxMembers>500</maxMembers>
    </event>
</events>
